name: Pipeline

on:
  push:
    branches: 
      - deploy

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
         
      - name: setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2
        with: 
          arguments: test
          
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
         
      - name: Build
        uses: gradle/gradle-build-action@v2
        with: 
          arguments: shadowJar
      - name: Upload built Jar artifact
        uses: actions/upload-artifact@v3
        with:
          name: applicationJar
          path: esop-0.1-all.jar
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
         
      - name: Download built Jar artifact
        uses: actions/download-artifact@v3
        with:
          name: applicationJar
         
      - name: Copy built Jar to remote machine instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/libs/esop-0.1-all.jar,start.sh"
          target: "/app/"
       
      - name: startup the application
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: /bin/bash start.sh
       
         
        
