name: Infra Provision
on:
  pull_request:
    branches: [ tf ]

jobs:
  plan:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
        
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    
    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Validate
      id: validate
      run: terraform validate
    
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -out="tf-plan"
      
    - name: upload Plan to Github Artifactory
      uses: actions/upload-artifact@v3
      with:
        name: tf-plan-${{github.event.pull_request.head.sha}}
        path: terraform/tf-plan
      
    - uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      env:
        PLAN: "${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `
          ##### Terraform Plan
          \`\`\`
          ${process.env.PLAN}
          \`\`\`
          `
          
          github.rest.pulls.update({
            pull_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
          
      
